- SharedBuildProperties.props
- build.cake
- src/Solana.Unity.Programs/SysVars.cs
- src/Solana.Unity.Rpc/Core/Http/JsonRpcClient.cs
- src/Solana.Unity.Rpc/Solana.Unity.Rpc.csproj
Using UnityWebRequest when running inside Unity, as HttpClient is not fully supported in WebGL
> ⚠️ NOTE: Compilation with Debug target compile with HttpClient and can run the tests, while Release target can only run inside unity
>  
| Status  | Type  | ⚠️ Core Change |
| :---: | :---: | :---: | 
| Ready| Hotfix | Yes| 
_HttpClient is not fully supported by Unity WebGL_
_Runtime check if running in Unity and use UnityWebRequest instead of HttpClient_
- build.cake run tests using the Debug target, while the Release target contains the code to perform http requests with UnityWebRequest
> :ambulance: Fix execution on WebGl

- .github/workflows/dotnet.yml
- .github/workflows/publish.yml
- README.md
- build.cake
- src/Solana.Unity.Wallet/PrivateKey.cs
- test/Solana.Unity.Rpc.Test/TransactionBuilderTest.cs
Avoid failing with empty private key, allows the SDK to build transaction before having all the available signatures
| Ready | Hotfix | No |  |
The SDK Unity package needs to build transactions with account that may have an empty private key (e.g.: Phantom, before sending the transaction for signature)
Build the transaction and add an empty signature when the private key is empty
> :ambulance: Avoid failing with empty private key

- build.cake
- src/Solana.Unity.Rpc/Core/Http/JsonRpcClient.cs
- src/Solana.Unity.Rpc/Solana.Unity.Rpc.csproj
- src/Solana.Unity.Rpc/Utilities/RuntimePlatform.cs
Add ability to run without Unity
| Ready | Feature | No |  |
- Unable to run the library without unity
- Because of this it was difficult to test external packages using it as a dependency (without Unit Test Runner)
Runtime check if is running or not in a Unity app
> :zap: Add ability to run without Unity

- src/Solana.Unity.Rpc/IRpcClient.cs
- src/Solana.Unity.Rpc/SolanaRpcClient.cs
- src/Solana.Unity.Rpc/TransactionUtils.cs
Add transaction confirmation methods
| Status  | Type  | ⚠️ Core Change | Issues | PRs |
| :---: | :---: | :---: | :--: | :--: |
| Ready | Feature | No | #14 #16 | #15 #17 |
Missing methods to confirm/wait for transaction completion
Add to RpcClient:
- SendAndConfirmTransactionAsync
- SendAndConfirmTransaction
Add utils to confirm transaction with http pooling or websockets
- TransactionConfirmationUtils.ConfirmTransaction
Adding these methods reduces coverage a bit, tests would need websockets and connection to a node. It can be fixed by adding integration test on a local validator node. 
Leaving this for future work.
Closes #14
Closes #15 
Closes #16
Closes #17
> :sparkles: Add transaction confirmation methods

- src/Solana.Unity.Dex/Orca/Orca/OrcaDex.cs
- src/Solana.Unity.Dex/Orca/Orca/OrcaTokens.cs
- src/Solana.Unity.Dex/Orca/Quotes/Swap/SwapQuoteUtils.cs
- src/Solana.Unity.Dex/Orca/Ticks/TickArraySequence.cs
- src/Solana.Unity.Dex/Orca/Ticks/TickUtils.cs
- src/Solana.Unity.Extensions/TokenMintResolver.cs
- src/Solana.Unity.Rpc/Core/Http/CrossHttpClient.cs
- src/Solana.Unity.Rpc/Utilities/RuntimePlatforms.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/TxApi/FindWhirlpoolTests.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/UpdateFeesRewardsTests.cs
- test/Solana.Unity.Dex.Test/Orca/Utils/PoolTestUtils.cs
Fix Cross Http for WebGL. Larger downloads and some concurrent requests were failing.
| Ready |  Hotfix | No | - |
Swap quotes and token images download weren't working on WebGL due to it being single thread and some issues with UnityWebRequest: running a request while another is in progress result in an infinite loop with the current Unity version.
When running in WebGL web request are sent serially.
> :bug: Fix WebGL web request

- SharedBuildProperties.props
- src/Solana.Unity.Rpc/Core/Sockets/StreamingRpcClient.cs
- src/Solana.Unity.Rpc/Core/Sockets/WebSocketWrapper.cs
- src/Solana.Unity.Rpc/Solana.Unity.Rpc.csproj
- src/Solana.Unity.Rpc/SolanaStreamingRpcClient.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/OpenPositionWithMetadataTests.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/TxApi/OpenPositionWithMetadataTxApiTests.cs
- test/Solana.Unity.Rpc.Test/SolanaStreamingClientTest.cs
Streaming RPC was not working on Unity due not not fully supported websockets
| Ready | Hotfix | Yes |  |
Streaming RPC was not working on Unity due not not fully supported websockets
- Compiled latest websockets sharp for dotnet 2.0: https://github.com/garbles-labs/websocket-sharp
- Compiled NativeWebSockets for dotnet 2.0: https://github.com/garbles-labs/Solana.Unity-Core
The WebGL version rely on methods defined in a jslib, see releases for the latest version: https://github.com/garbles-labs/NativeWebSocket/releases
**New dependencies**:
- `native-websocket` : Unity compatible websockets
- `websocket-sharp-latest`: Latest websockets sharp compiled for dotnet 2.0
> :sparkles: Fix streaming RPC on Unity

- src/Solana.Unity.Examples/AssociatedTokenAccountsExample.cs
- src/Solana.Unity.Examples/ExampleHelpers.cs
- src/Solana.Unity.Examples/GetTokenAccountsByOwnerExample.cs
- src/Solana.Unity.Examples/HelloWorldExample.cs
- src/Solana.Unity.Examples/IExample.cs
- src/Solana.Unity.Examples/InstructionDecoderExample.cs
- src/Solana.Unity.Examples/MultisigExamples.cs
- src/Solana.Unity.Examples/NameServiceClientExample.cs
- src/Solana.Unity.Examples/NameServiceProgramExamples.cs
- src/Solana.Unity.Examples/SolanaKeygenKeyGeneration.cs
- src/Solana.Unity.Examples/SolletKeyGeneration.cs
- src/Solana.Unity.Examples/SolletKeygenKeystore.cs
- src/Solana.Unity.Examples/StakeExample.cs
- src/Solana.Unity.Examples/TokenSwapExample.cs
- src/Solana.Unity.Examples/TokenWalletExample.cs
- src/Solana.Unity.Examples/TransactionBuilderExample.cs
- src/Solana.Unity.Examples/TransactionDecodingExample.cs
- src/Solana.Unity.Extensions/TokenWallet.cs
- src/Solana.Unity.Rpc/Core/Http/JsonRpcClient.cs
- src/Solana.Unity.Rpc/IRpcClient.cs
- test/Solana.Unity.Extensions.Test/TokenWalletTest.cs
| Ready |  Hotfix | Yes | - |
Many synch version of async methods are blocking the main thread on Unity.
See https://stackoverflow.com/questions/14526377/why-does-this-async-action-hang-when-i-try-and-access-the-result-property-of-my for more details on the issue.
Since sync over async is not generally a good design pattern, removed the sync version of the methods
> :ambulance: Remove sync methods blocking main thread on Unity

- src/Solana.Unity.Dex/Orca/Orca/OrcaTokens.cs
- src/Solana.Unity.Dex/Orca/Orca/TokensDocument.cs
- src/Solana.Unity.Dex/Resources/link.xml
- src/Solana.Unity.Dex/Solana.Unity.Dex.csproj
- src/Solana.Unity.Examples/TokenWalletExample.cs
- src/Solana.Unity.Extensions/ITokenMintResolver.cs
- src/Solana.Unity.Extensions/Models/TokenMint/TokenDef.cs
- src/Solana.Unity.Extensions/Models/TokenWallet/TokenQuantity.cs
- src/Solana.Unity.Extensions/Models/TokenWallet/TokenWalletAccount.cs
- src/Solana.Unity.Extensions/Models/TokenWallet/TokenWalletBalance.cs
- src/Solana.Unity.Extensions/Models/TokenWallet/TokenWalletFilterList.cs
- src/Solana.Unity.Extensions/Resources/link.xml
- src/Solana.Unity.Extensions/Solana.Unity.Extensions.csproj
- src/Solana.Unity.Extensions/TokenMintResolver.cs
- src/Solana.Unity.Extensions/TokenWallet.cs
- src/Solana.Unity.Extensions/WellKnownTokens.cs
- src/Solana.Unity.Rpc/Resources/link.xml
- src/Solana.Unity.Rpc/Solana.Unity.Rpc.csproj
- test/Solana.Unity.Extensions.Test/TokenMintTest.cs
- test/Solana.Unity.Extensions.Test/TokenWalletTest.cs
| Ready | Hotfix | No | https://github.com/magicblock-labs/Solana.Unity-SDK/issues/69 |
Unity was stripping code needed for serialising/deserialising classes used at runtime 
Added link.xml to prevent il2cpp compiler to strip classes and replace `IList` with `List`, following suggestion from: https://github.com/JamesNK/Newtonsoft.Json/issues/1521
> :bug: Fix unity code stripping

- src/Solana.Unity.Rpc/Core/Http/CrossHttpClient.cs
- src/Solana.Unity.Rpc/SolanaStreamingRpcClient.cs
- src/Solana.Unity.Rpc/Utilities/RuntimePlatforms.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/ClosePositionTests.cs
| Ready |  Hotfix | No | - |
Using Mono, on Android build platform the System.Net.Http client doesn't work
Changing the CrossHttp client to use UnityWebRequest instead, that does worl.
> :bug: Fix missing classes when code stripping is set to high on android

- src/Solana.Unity.Rpc/TransactionUtils.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/TxApi/ClosePositionTxApiTests.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/TxApi/SwapTxApiTests.cs
- test/Solana.Unity.Rpc.Test/Integrations/TestConfiguration.cs
- test/Solana.Unity.Rpc.Test/Integrations/TransactionUtilsTest.cs
| Hold | Feature/Bug | No | https://github.com/magicblock-labs/Solana.Unity-SDK/issues/154 |
See #154
Use signature subscription and remove awaits
> :bug: Fix transaction confirmation

- src/Solana.Unity.Rpc/IRpcClient.cs
- src/Solana.Unity.Rpc/Models/Block.cs
- src/Solana.Unity.Rpc/SolanaRpcClient.cs
- test/Solana.Unity.Rpc.Test/Resources/Http/Blocks/GetLatestBlockhashRequest.json
- test/Solana.Unity.Rpc.Test/Resources/Http/Blocks/GetLatestBlockhashResponse.json
- test/Solana.Unity.Rpc.Test/Solana.Unity.Rpc.Test.csproj
- test/Solana.Unity.Rpc.Test/SolanaRpcClientBlockTests.cs
| Ready | Feature | No | https://github.com/magicblock-labs/Solana.Unity-SDK/issues/155 |
Missing GetLatestBlockHash
Add GetLatestBlockHash
Closes https://github.com/magicblock-labs/Solana.Unity-SDK/issues/155
> :heavy_plus_sign: Add GetLatestBlockHash method

- src/Solana.Unity.Rpc/IRpcClient.cs
- src/Solana.Unity.Rpc/SolanaRpcClient.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/TxApi/CollectFeesTxApiTests.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/TxApi/DecreaseLiquidityTxApiTests.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/UpdateFeesRewardsTests.cs
- test/Solana.Unity.Rpc.Test/Integrations/TransactionUtilsTest.cs
| Ready/  | Feature | No | -  |
Default commitment not configurable after RPC initialization
Make default commitment configurable from external
Closes #34
> :zap: Make default commitment configurable from external

- src/Solana.Unity.Rpc/Core/Http/CrossHttpClient.cs
| Ready | Bug | No | https://github.com/magicblock-labs/Solana.Unity-SDK/issues/163 |
See https://github.com/magicblock-labs/Solana.Unity-SDK/issues/163
Set the task to null on exception
> :bug: Fix CrossHttpClient Failing requests

- src/Solana.Unity.Dex/IDexAggregator.cs
- src/Solana.Unity.Dex/Jupiter/Core/Types/Http/SwapRequest.cs
- src/Solana.Unity.Dex/Jupiter/Core/Types/Http/SwapResponse.cs
- src/Solana.Unity.Dex/Jupiter/JupiterDex.cs
- src/Solana.Unity.Dex/Models/TokenData.cs
- src/Solana.Unity.Dex/Models/TokenListType.cs
- src/Solana.Unity.Dex/Quotes/SwapQuoteAg.cs
- src/Solana.Unity.Rpc/Core/Http/CrossHttpClient.cs
- test/Solana.Unity.Dex.Test/Jupiter/Integration/JupiterTests.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/TxApi/ClosePositionTxApiTests.cs
| Ready  | Feature  | No | - |
Missing a Dex Aggreagator
- Defined an interface IDexAggregator with commons methods for getting quotes e swap transactions, following the [Jupiter API](https://station.jup.ag/docs/apis) documentation
- Concrete implementation for the Jupiter Aggregator
- Added methods for getting a quote, retrieving the swap transaction and retrieving tokens by symbol or mint.
> :sparkles: Add IDexAggregator interface & Jupiter implementation

- SharedBuildProperties.props
- src/Solana.Unity.Dex/Jupiter/JupiterDex.cs
- src/Solana.Unity.Rpc/Builders/MessageBuilder.cs
- src/Solana.Unity.Rpc/Builders/VersionedMessageBuilder.cs
- src/Solana.Unity.Rpc/Core/Http/CrossHttpClient.cs
- src/Solana.Unity.Rpc/Models/AccountKeysList.cs
- src/Solana.Unity.Rpc/Models/Message.cs
- src/Solana.Unity.Rpc/Models/Transaction.cs
- src/Solana.Unity.Rpc/Models/VersionedMessage.cs
- src/Solana.Unity.Rpc/Models/VersionedTransaction.cs
- src/Solana.Unity.Rpc/Models/VersionedTransactionInstruction.cs
- test/Solana.Unity.Dex.Test/Jupiter/Integration/JupiterTests.cs
- test/Solana.Unity.Rpc.Test/VersionedMessageTest.cs
- test/Solana.Unity.Rpc.Test/VersionedTransactionTest.cs
| Ready | Feature | Yes | #43 |
- [Versioned Transactions](https://docs.solana.com/developing/versioned-transactions) were not supported, see issue #43
- Added a VersionedTransaction class which can serialize/deserialize [Versioned Transactions](https://docs.solana.com/developing/versioned-transactions), implemented following web3.js [implementation](https://github.com/solana-labs/solana-web3.js/blob/master/packages/library-legacy/src/transaction/versioned.ts) 
- VersionedTransaction contains the `AddressTableLookups`
- `Transaction.Deserialize` use the prefix byte to auto-detected if the transaction is legacy or versioned and uses the correct implementation
> :sparkles: Implement Versioned Transactions

- src/Solana.Unity.Dex/IDexAggregator.cs
- src/Solana.Unity.Dex/Jupiter/JupiterDex.cs
- src/Solana.Unity.Dex/Solana.Unity.Dex.csproj
- test/Solana.Unity.Dex.Test/Jupiter/Integration/JupiterTests.cs
| Ready | Feature  | No | - |
Swap mode not supported 
Added Swap mode in accordance with: https://station.jup.ag/docs/v6-beta/payments-api
> :sparkles: Add SwapMode to allow ExactOut mode with Jupiter

- src/Solana.Unity.Rpc/IRpcClient.cs
- src/Solana.Unity.Rpc/SolanaRpcClient.cs
- test/Solana.Unity.Rpc.Test/Resources/Http/Transaction/GetTransactionProcessedRequest.json
- test/Solana.Unity.Rpc.Test/Resources/Http/Transaction/GetTransactionRequest.json
Add maxSupportedTransactionVersion to GetTransactionAsync
| Ready | Feature | No | https://github.com/magicblock-labs/Solana.Unity-SDK/issues/187 |
See https://github.com/magicblock-labs/Solana.Unity-SDK/issues/187
Added `maxSupportedTransactionVersion` parameter to `GetTransactionAsync`
> :sparkles: Add maxSupportedTransactionVersion

- SharedBuildProperties.props
- src/Solana.Unity.Rpc/Core/Sockets/IWebSocket.cs
- src/Solana.Unity.Rpc/Core/Sockets/StreamingRpcClient.cs
- src/Solana.Unity.Rpc/Core/Sockets/SubscriptionState.cs
- src/Solana.Unity.Rpc/Core/Sockets/WebSocketWrapper.cs
- src/Solana.Unity.Rpc/IStreamingRpcClient.cs
- src/Solana.Unity.Rpc/Solana.Unity.Rpc.csproj
- src/Solana.Unity.Rpc/SolanaStreamingRpcClient.cs
- test/Solana.Unity.Rpc.Test/SolanaStreamingClientTest.cs
| Ready | Feature | No | https://github.com/magicblock-labs/Solana.Unity-SDK/issues/184, https://github.com/magicblock-labs/Solana.Unity-SDK/issues/182,  https://github.com/magicblock-labs/Solana.Unity-SDK/issues/183|
- See https://github.com/magicblock-labs/Solana.Unity-SDK/issues/184, https://github.com/magicblock-labs/Solana.Unity-SDK/issues/182,  https://github.com/magicblock-labs/Solana.Unity-SDK/issues/183 for detailed descriptions
- Default values for localhost
- WebSockets now try to reconnect when losing connection
- Global settable default Commitment for IStreamingRpc
- Several fixes in the Websockets, removed the need for a dispatcher object and replaced infinite loop with events
>  Fix and Improve Streaming Rpc

- src/Solana.Unity.Dex/Orca/Orca/OrcaDex.cs
- src/Solana.Unity.Dex/Orca/SolanaApi/SystemUtils.cs
- src/Solana.Unity.Dex/Orca/SolanaApi/TokenUtilsTransaction.cs
- src/Solana.Unity.Examples/AssociatedTokenAccountsExample.cs
- src/Solana.Unity.Examples/HelloWorldExample.cs
- src/Solana.Unity.Examples/InstructionDecoderExample.cs
- src/Solana.Unity.Examples/MultisigExamples.cs
- src/Solana.Unity.Examples/NameServiceProgramExamples.cs
- src/Solana.Unity.Examples/StakeExample.cs
- src/Solana.Unity.Examples/TokenSwapExample.cs
- src/Solana.Unity.Examples/TransactionBuilderExample.cs
- src/Solana.Unity.Examples/TransactionDecodingExample.cs
- src/Solana.Unity.Programs/Abstract/TransactionalBaseClient.cs
- test/Solana.Unity.Dex.Test/Orca/Integration/IncreaseLiquidityTests.cs
- test/Solana.Unity.Dex.Test/Orca/Utils/LiquidityTestUtils.cs
- test/Solana.Unity.Dex.Test/Orca/Utils/TokenUtils.cs
| Ready | Hotfix | No |  |
GetRecentBlockHash is deprecated and some Nodes do not support this call anymore (ie Helius)
Replaced all the calls with GetLatestBlockHash() which is the advised RPC Call.
> Updated GetRecentBlockHash to GetLatestBlockHash

- src/Solana.Unity.Rpc/ClientFactory.cs
- src/Solana.Unity.Rpc/Core/Sockets/StreamingRpcClient.cs
- src/Solana.Unity.Rpc/Core/Sockets/WebSocketWrapper.cs
- src/Solana.Unity.Rpc/SolanaStreamingRpcClient.cs
| Ready | Bug | No | - |
- Under caertain circumstances, the main thread was locked on `connect_async` and `disconnect_async`
- Unable to use a custom IWebsocket implementation
- Fixed awaiter and async
- Added an overload method on `ClientFactory.GetStreamingClient` that allow to pass an `IWebsocket` instance
> fix: streaming rpc

- src/Solana.Unity.Extensions/Models/TokenWallet/TokenQuantity.cs
- src/Solana.Unity.Extensions/Models/TokenWallet/TokenWalletBalance.cs
- src/Solana.Unity.KeyStore/Solana.Unity.KeyStore.csproj
- src/Solana.Unity.Wallet/Bip39/Mnemonic.cs
- src/Solana.Unity.Wallet/Solana.Unity.Wallet.csproj
> ⚠️ NOTE: Use notes like this to emphasize something important about the PR.
>  
>  This could include other PRs this PR is built on top of; API breaking changes; reasons for why the PR is on hold; or anything else you would like to draw attention to.
| **Draft** | **Refactor**| ? | [Link](<Issue link here>) |
`Solana.Unity-Core` relies on a deprecated unofficial fork of the BouncyCastle cryptography library, `Portable.BouncyCastle`, which hasn't been updated for ~5 years.
There're 3 vulnerability found in the original version of the old [BouncyCastle library](https://www.nuget.org/packages/BouncyCastle/1.8.9):
In addition to the potential security risk, it introduces a dependency conflict in Unity with …
> Migrate to official BouncyCastle.Cryptography
